server:
  port: 8080

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/review
    password: postgres
    username: postgres
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    enabled: true
    path: /reviews/swagger-ui.html
  api-docs:
    enabled: true
    path: /reviews/swagger-ui/v3/api-docs